# Generated by Django 5.2.4 on 2025-08-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='attestation_type',
            field=models.CharField(choices=[('зачет', 'Зачет'), ('экзамен', 'Экзамен')], max_length=10, null=True),
        ),
    ]
