# Generated by Django 5.2.4 on 2025-08-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_discipline_attestation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='attestation_type',
            field=models.CharField(choices=[('зачет', 'Зачет'), ('экзамен', 'Экзамен')], max_length=10),
        ),
    ]
