# Generated by Django 5.2.1 on 2025-06-02 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('groups', models.ManyToManyField(related_name='courses', to='authentication.group')),
                ('teachers', models.ManyToManyField(limit_choices_to={'role': 'Преподаватель'}, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoursePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Лекция', 'Лекция'), ('Практика', 'Практика'), ('Семинар', 'Семинар'), ('Лабораторная', 'Лабораторная'), ('Аттестация', 'Аттестация')], max_length=50)),
                ('hours_allocated', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='universityjournalback.discipline')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('Лекция', 'Лекция'), ('Практика', 'Практика'), ('Семинар', 'Семинар'), ('Лабораторная', 'Лабораторная'), ('Аттестация', 'Аттестация')], max_length=50)),
                ('topic', models.CharField(max_length=255, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='universityjournalback.discipline')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('н', 'Отсутствовал'), ('п', 'Присутствовал')], max_length=1)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'Студент'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universityjournalback.session')),
            ],
        ),
    ]
