# Generated by Django 5.2.1 on 2025-05-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityjournalback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='topic',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
