# Generated by Django 5.2.1 on 2025-06-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityjournalback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseplan',
            name='hours_per_session',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
