# Generated by Django 5.2.1 on 2025-05-30 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityjournalback', '0002_session_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Лекция', 'Лекция'), ('Практика', 'Практика'), ('Семинар', 'Семинар'), ('Лабораторная', 'Лабораторная'), ('Аттестация', 'Аттестация')], max_length=50)),
                ('hours_allocated', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='universityjournalback.course')),
            ],
        ),
    ]
