# Generated by Django 5.2 on 2025-05-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_group_user_group'),
        ('universityjournalback', '0002_course_group_alter_session_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='group',
        ),
        migrations.AddField(
            model_name='course',
            name='groups',
            field=models.ManyToManyField(related_name='courses', to='authentication.group'),
        ),
    ]
