# Generated by Django 5.2.1 on 2025-06-06 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universityjournalback', '0002_courseplan_hours_per_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseplan',
            name='hours_per_session',
        ),
    ]
