# Generated by Django 5.2.3 on 2025-06-18 09:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityjournalback', '0003_remove_courseplan_hours_per_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='teachers',
            field=models.ManyToManyField(limit_choices_to={'role': 'Преподаватель'}, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
