# Generated by Django 5.2 on 2025-05-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityjournalback', '0003_remove_course_group_course_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='type',
            field=models.CharField(choices=[('Лекция', 'Лекция'), ('Практика', 'Практика'), ('Семинар', 'Семинар'), ('Лаб', 'Лабораторная'), ('Аттестация', 'Аттестация')], max_length=50),
        ),
    ]
