# Generated by Django 5.2.3 on 2025-06-18 09:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityjournalback', '0004_alter_discipline_teachers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='teachers',
            field=models.ManyToManyField(limit_choices_to={'role': 'Преподаватель'}, to=settings.AUTH_USER_MODEL),
        ),
    ]
