# Generated by Django 5.2.3 on 2025-06-18 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityjournalback', '0005_alter_discipline_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplinePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_per_session', models.PositiveIntegerField(default=2)),
                ('type', models.CharField(choices=[('Лекция', 'Лекция'), ('Практика', 'Практика'), ('Семинар', 'Семинар'), ('Лабораторная', 'Лабораторная'), ('Аттестация', 'Аттестация')], max_length=50)),
                ('hours_allocated', models.PositiveIntegerField()),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='universityjournalback.discipline')),
            ],
        ),
        migrations.DeleteModel(
            name='CoursePlan',
        ),
    ]
