# Generated by Django 5.2.3 on 2025-06-19 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_group_student_user_group'),
        ('universityjournalback', '0006_disciplineplan_delete_courseplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='authentication.group'),
            preserve_default=False,
        ),
    ]
