# Generated by Django 5.2.4 on 2025-07-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityjournalback', '0009_attendance_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('ув', 'Отсутствовал по уважительной причине'), ('неув', 'Отсутствовал по неуважительной причине'), (' ', 'Присутствовал')], max_length=4),
        ),
    ]
