# Generated by Django 5.2.4 on 2025-07-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityjournalback', '0010_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplineplan',
            name='is_group_splited',
            field=models.BooleanField(null=True),
        ),
    ]
