# Generated by Django 5.2.4 on 2025-07-09 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universityjournalback', '0011_disciplineplan_is_group_splited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disciplineplan',
            old_name='is_group_splited',
            new_name='is_group_split',
        ),
    ]
