# Generated by Django 5.2.4 on 2025-07-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityjournalback', '0012_rename_is_group_splited_disciplineplan_is_group_split'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplineplan',
            name='is_group_split',
        ),
        migrations.AddField(
            model_name='discipline',
            name='is_group_split',
            field=models.BooleanField(null=True),
        ),
    ]
