# Generated by Django 5.2.4 on 2025-07-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityjournalback', '0013_remove_disciplineplan_is_group_split_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='subGroup',
            field=models.IntegerField(null=True),
        ),
    ]
