# Generated by Django 5.2.4 on 2025-07-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityjournalback', '0014_session_subgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='subGroup',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
