# Generated by Django 5.2.4 on 2025-07-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityjournalback', '0015_alter_session_subgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplineplan',
            name='type',
            field=models.CharField(choices=[('Лекция', 'Лекция'), ('Практика', 'Практика'), ('Семинар', 'Семинар'), ('Лабораторная', 'Лабораторная'), ('УСР', 'УСР')], max_length=50),
        ),
        migrations.AlterField(
            model_name='session',
            name='type',
            field=models.CharField(choices=[('Лекция', 'Лекция'), ('Практика', 'Практика'), ('Семинар', 'Семинар'), ('Лабораторная', 'Лабораторная'), ('УСР', 'УСР')], max_length=50),
        ),
    ]
