# Generated by Django 5.2.1 on 2025-06-03 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.faculty'),
        ),
    ]
