# Generated by Django 5.2.2 on 2025-06-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_studentprofile_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/teachers/'),
        ),
    ]
