# Generated by Django 5.2.11 on 2026-02-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_user_group_remove_user_isheadman_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
