# Generated by Django 5.2.2 on 2025-06-09 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_teacherprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
