# Generated by Django 5.2.2 on 2025-06-10 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_group_students_delete_studentprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group_name',
            new_name='name',
        ),
    ]
