# Generated by Django 5.2.2 on 2025-06-10 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_rename_group_name_group_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='students',
            new_name='student',
        ),
    ]
