# Generated by Django 5.2.3 on 2025-07-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_group_student_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isHeadman',
            field=models.BooleanField(null=True),
        ),
    ]
