# Generated by Django 5.2.4 on 2025-07-15 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_user_subgroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='subgroup',
            new_name='subGroup',
        ),
    ]
