# Generated by Django 5.2.4 on 2025-07-20 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attestation', '0001_initial'),
        ('authentication', '0001_initial'),
        ('journal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attestationresult',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestation_results', to='journal.discipline'),
        ),
        migrations.AddField(
            model_name='attestationresult',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestation_results', to='authentication.group'),
        ),
        migrations.AddField(
            model_name='attestationresult',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'Студент'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usr',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usr_results', to='journal.discipline'),
        ),
        migrations.AddField(
            model_name='usr',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.group'),
        ),
        migrations.AddField(
            model_name='usr',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'Студент'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='attestationresult',
            unique_together={('student', 'discipline')},
        ),
        migrations.AlterUniqueTogether(
            name='usr',
            unique_together={('student', 'discipline')},
        ),
    ]
