# Generated by Django 5.2.4 on 2025-07-20 14:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0002_initial'),
        ('authentication', '0001_initial'),
        ('journal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttestationResult',
            new_name='Attestation',
        ),
    ]
