# Generated by Django 5.2.4 on 2025-08-04 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0003_rename_attestationresult_attestation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usr',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usr',
            name='attestation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usr_items', to='attestation.attestation'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='usr',
            name='discipline',
        ),
        migrations.RemoveField(
            model_name='usr',
            name='group',
        ),
        migrations.RemoveField(
            model_name='usr',
            name='student',
        ),
    ]
