# Generated by Django 5.2.4 on 2025-08-08 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0004_alter_usr_unique_together_usr_attestation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attestation',
            name='attestation_type',
        ),
    ]
